camaaloth:
  recordingDir: "${HOME}/Videos"
  copyScript: "${HOME}/camaaloth/nageru/copy.sh"
  preRecordScript: "${HOME}/tv-display/local/stop.sh"
  postRecordScript: "${HOME}/tv-display/local/start.sh"
  nageru:
    startScript: "${HOME}/camaaloth/nageru/launch-nageru.sh"
    themeDir: "${HOME}/camaaloth/nageru/themes"
  breizhcamp:
    arduinoPort: auto
    scheduleFiles:
      - "${HOME}/camaaloth/launcher/schedule.json"
      - "${HOME}/camaaloth/launcher/talks_others.json"
    copyDir: "videos"
    copyServer: "rsync://192.168.1.2/"


